### PR TITLE
Fixing event listener overloads

### PR DESCRIPTION
**Pull request by Skillz4Killz**
This PR fixes the event listeners for Yuuko.
It will no longer override the Eris listeners with the default string overload and just defaults to Eris overloads if none is found in Yuuko.

Note: This PR is pending merging of Eris #dev into master so we can access the interfaces created there and extend those interfaces inside Yuuko. https://github.com/abalabahaha/eris/pull/575

### CODE REVIEW

**Comment by eritbh** [comment]
Solid solution, thanks for this! I'll make sure it gets merged once there's a new Eris release with the upstream changes.

**Comment by eritbh** [comment]
Don't think you meant to push that last commit to this branch...

**Comment by Skillz4Killz** [comment]
Whoopsies, ill get that fixed!

**Comment by Skillz4Killz** [comment]
I believe this should now be ready for review @Geo1088 Eris got updated last night.

**Comment by eritbh** [comment]
Thanks again!

**Pull request merged**
